export type PacketStatus = "draft" | "reviewing" | "ready" | "sent";

// 한 회사 공고에 지원하기 위한 자료, 저장소, 메모, 보완 작업을 묶은 단위
export type ApplicationPacket = {
    // 한 회사 공고에 지원하기 위한 준비 묶음의 고유 ID
    id: string;
    // 지원할 회사 이름
    companyName: string;
    jobTitle: string;
    // 지원할 포지션 이름
    jobPostingUrl?: string;
    jobPostingText: string;
    status: PacketStatus;
    repoUrls: string[];
    attachments: PacketAttachment[];
    notes: string;
    checkItems: PacketCheckItem[];
    remediationTasks: RemediationTask[];
    createdAt: string;
    updatedAt: string;
};

export type PacketAttachment = {
    id: string;
    fileName: string;
    fileKind: "resume" | "portfolio" | "screenshot" | "etc";
    externalUrl?: string;
    purposeNote: string;
};

export type CheckItemStatus = "passed" | "warning" | "missing";

export type PacketCheckItem = {
    id: string;
    label: string;
    status: CheckItemStatus;
    evidence: string;
    autoGenerated: boolean;
    confirmedByUser: boolean;
};

export type RemediationPriority = "high" | "medium" | "low";

export type RemediationTask = {
    id: string;
    title: string;
    description: string;
    priority: RemediationPriority;
    status: "todo" | "done";
};
