export type PacketStatus = "draft" | "reviewing" | "ready" | "sent";

export type ApplicationPacket = {
    id: string;
    companyName: string;
    jobTitle: string;
    jobPostingUrl?: string;
    jobPostingText: string;
    status: PacketStatus;
    repoUrls: string[];
    attachments: PacketAttachment[];
    notes: string;
    checkItems: PacketCheckItem[];
    remediationTasks: RemediationTask[];
    createdAt: string;
    updatedAt: string;
};

export type PacketAttachment = {
    id: string;
    fileName: string;
    fileKind: "resume" | "portfolio" | "screenshot" | "etc";
    externalUrl?: string;
    purposeNote: string;
};

export type CheckItemStatus = "passed" | "warning" | "missing";

export type PacketCheckItem = {
    id: string;
    label: string;
    status: CheckItemStatus;
    evidence: string;
    autoGenerated: boolean;
    confirmedByUser: boolean;
};

export type RemediationPriority = "high" | "medium" | "low";

export type RemediationTask = {
    id: string;
    title: string;
    description: string;
    priority: RemediationPriority;
    status: "todo" | "done";
};
